import type { Metadata } from "next";
import localFont from "next/font/local";

import "./globals.css";
import "./styles.css";
import "swiper/css";
import "swiper/css/pagination";

import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";

import { ThemeProvider } from "./theme-provider";
import AppkitContextProvider from "@/context/appkit";

import Link from "next/link";
import { headers } from "next/headers"; // added

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookies = headers().get("cookie");
  return (
    <html lang="en">
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AppkitContextProvider cookies={cookies}>
            <div className="relative flex h-screen flex-col">
              <Navbar />
              <main className="container mx-auto max-w-[2560px] flex-grow px-6 pt-16">
                {children}
              </main>
              {/* <footer className="flex w-full items-center justify-center py-3">
                <Link
                  className="flex items-center gap-1 text-current"
                  href="https://nextui-docs-v2.vercel.app?utm_source=next-app-template"
                  title="nextui.org homepage"
                >
                  <span className="text-default-600">Powered by</span>
                  <p className="text-primary">NextUI</p>
                </Link>
              </footer> */}
            </div>
          </AppkitContextProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
